# Date: Sept 2024
# Author: Jakub Malecki
# Purpose: This code displays an app menu

print("\t| ▶ ＹｏｕＴｕｂｅ  |")
print("\t_________________________________________________")
print("\t|🏠  Home \t    | \t\t\t\t|")
print("\t|🔃 Shorts \t    | \t\t\t\t|")
print("\t|✔ Subscriptions   | \t\t\t\t|")
print("\t|-----------------------------------------------|")
print("\t|𝙁𝙊𝙍 𝙔𝙊𝙐 \/ \t\t\t\t\t|\n\t|\t\t\t\t\t\t|")
print("\t|👤  Your Channel \t\t\t\t|")
print("\t|⏰ History\t\t\t\t\t|")
print("\t|📂 Playlists \t\t\t\t\t|")
print("\t|📹 Your Videos \t\t\t\t\t|")
print("\t|⌛ Watch Later \t\t\t\t\t|")
print("\t|👍 Liked Videos \t\t\t\t|")
print("\t|✂ Clips\t\t\t\t\t|")
print("\t|-----------------------------------------------|")
print("\t|𝐒𝐮𝐛𝐬𝐜𝐫𝐢𝐩𝐭𝐢𝐨𝐧𝐬\/\t\t\t\t\t|")
print("\t|👤 Jeff Nippard\t\t\t\t\t|")
print("\t|👤 Pitbull\t\t\t\t\t|")
print("\t|👤 Daniel Cutting\t\t\t\t|")
print("\t|👤 CCC\t\t\t\t\t\t|")
print("\t|📋 All subscriptions\t\t\t\t|")
print("\t|-----------------------------------------------|")
print("\t|𝐄𝐱𝐩𝐥𝐨𝐫𝐞\t\t\t\t\t\t|\n\t|\t\t\t\t\t\t|")
print("\t|🔥 Trending\t\t\t\t\t|")
print("\t|🎵 Music\t\t\t\t\t|")
print("\t|🎬 Films\t\t\t\t\t|")
print("\t|🎮 Games\t\t\t\t\t|")
print("\t|📃 News\t\t\t\t\t\t|")
print("\t|🏅 Sports\t\t\t\t\t|")
print("\t|🎙 Podcasts\t\t\t\t\t|")
print("\t|-----------------------------------------------|")
print("\t|▶️YouTube Premium\t\t\t\t|")
print("\t|▶🎵 YouTube Music\t\t\t\t|")
print("\t|▶🎙 YouTube Podcasts\t\t\t\t|")
print("\t|▶👶 YouTube Kids\t\t\t\t|")
print("\t|-----------------------------------------------|")
print("\t|⚙️ Settings\t\t\t\t\t|")
print("\t|🏴 Report\t\t\t\t\t|")
print("\t|❓ Help\t\t\t\t\t\t|")
print("\t|⁉ Send Feedback\t\t\t\t\t|")
print("\t|_______________________________________________|")
